# This is a basic workflow to help you get started with Actions
name: 01-Validate-and-Deploy-IaC
on: [push]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.9

      - name: Validate and check terraform format
        run: |
          terraform init -backend=false
          terraform fmt -check
          terraform validate
release:
    needs: validate
    runs-on: ubuntu-latest
    env:
      USER_STAGE: "WNowak"
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    steps:
      - uses: actions/checkout@v3
     
      - name: Create terraform plan
        run: |
          terraform init -backend-config="./config/${{env.USER_STAGE}}/backend.conf"
          terraform plan -var-file="./config/${{env.USER_STAGE}}/env.tfvars" -out plan
     
      - name: Apply terraform plan
        run: |
          terraform init -backend-config="./config/${{env.USER_STAGE}}/backend.conf"
          terraform apply plan
